# PostgreSQL
#
development:
  adapter: postgresql
  encoding: unicode
  database: minniesplace_development
  pool: 5
  username: mcalhoun
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: minniesplace_test
  pool: 5
  username: mcalhoun
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: minniesplace_production
  pool: 5
  username: mcalhoun
  password: 
